name: Branch Deployement

on:
  push:
    branches:
      - main

jobs:
  Dev_Deployment:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build and Test
        run: |
          # Add your build and test commands here
          echo "Running build and tests for Dev"
      - name: Deploy to Dev
        run: |
          # Add your deployment script/commands for Dev environment here
          echo "Deploying to Dev environment"

  UAT_Deployment:
    runs-on: ubuntu-latest
    environment: UAT
    needs: Dev_Deployment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Deploy to UAT
        run: |
          # Add your deployment script/commands for UAT environment here
          echo "Deploying to UAT environment"

  Prod_Deployment:
    runs-on: ubuntu-latest
    environment: Prod
    needs: UAT_Deployment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Deploy to Prod
        run: |
          # Add your deployment script/commands for Prod environment here
          echo "Deploying to Prod environment"

  Propagate_Dev_Branch:
    runs-on: ubuntu-latest
    needs: Prod_Deployment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.email "nishanthkmb97@gmail.com"
          git config --global user.name "Nishanth"
      - name: Push changes to Dev branch
        run: |
          git checkout Dev
          git merge main
          git push origin Dev

  Propagate_UAT_Branch:
    runs-on: ubuntu-latest
    needs: Propagate_Dev_Branch
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.email "nishanthkmb97@gmail.com"
          git config --global user.name "Nishanth"
      - name: Push changes to UAT branch
        run: |
          git checkout UAT
          git merge Dev
          git push origin UAT

  Propagate_Prod_Branch:
    runs-on: ubuntu-latest
    needs: Propagate_UAT_Branch
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.email "nishanthkmb97@gmail.com"
          git config --global user.name "Nishanth"
      - name: Push changes to Prod branch
        run: |
          git checkout Prod
          git merge UAT
          git push origin Prod
